### ISSUE TITLE
状态栏的流量状态永远显示0kb

### ISSUE THREAD

**Issue by MrSeven590** [NetchX/NetchMode#44]
实测在加速Minecraft的时候，状态栏永远显示0kb，但实际上是有加速效果的
版本为1.3.4

**Comment by EKyero** [comment]
@MrSeven590 请自行阅读readme

**Comment by BingLingGroup** [comment]
issue 投错位置了

**Comment by BingLingGroup** [comment]
请查看 [Netch.1.3.2 的更新日志](https://github.com/NetchX/Netch/blob/master/docs/CHANGELOG.zh-CN.md#132---2019-09-29)

**Comment by MrSeven590** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"BingLingGroup"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月10日(星期天) 晚上7:13
收件人:&nbsp;"NetchX/NetchMode"<NetchMode@noreply.github.com&gt;;
抄送:&nbsp;"Mr.Seven"<mr_seven590@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [NetchX/NetchMode] 状态栏的流量状态永远显示0kb (#44)




请查看 Netch.1.3.2 的更新日志
